name: expressions-example
on:
  push:

jobs:
  use-expressions:
    strategy:
      fail-fast: false
      matrix:
        greeting: [Hello, Howdy, Hey]
    runs-on: ubuntu-latest
    steps:
      - name: Print if 'Hello'
        if: ${{ matrix.greeting== 'Hello'}}
        run: echo "greeting is Hello"

      - name: Print if starts with 'He'
        if: ${{ startsWith( matrix.greeting,'He' )}}
        run: echo "greeting starts with He"

      - name: Print if ends with 'y'
        if: ${{ endsWith( matrix.greeting,'He' )}}
        run: echo "greeting ends with He"

      - name: Print formatted greeting
        run: |
          echo "${{ format('{0} says {1}',github.actor,matrix.greeting)}}"

      - name: From JSON
        if: ${{ fromJSON(' {"FAVORITE_FRUIT":"APPLE", "FAVORITE_COLOR":"BLUE" }' ) }}
        run: echo "I would like a ${FAVORITE_COLOR} ${FAVORITE_FRUIT}"

      - name: Success
        if: ${{ success() }}
        run: echo "You will always see this"
