name: parallel-jobs
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work parallel with job2"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work parallel with job1"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Doing work after job1"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo "Doing work after job2,job3"

  job5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: job1
    steps:
      - run: echo "job1 completed with status ${{ needs.job1.result }}, running job5"
